# Generated by Django 3.1.7 on 2021-03-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('Event_name', models.CharField(max_length=50)),
                ('Event_type', models.CharField(choices=[('BA', 'Batlle'), ('WO', 'Workshop'), ('CL', 'Classes')], default='', max_length=2)),
                ('Event_category', models.CharField(choices=[('HH', 'HIP-HOP'), ('PP', 'Popping'), ('BR', 'Breaking')], default='', max_length=2)),
                ('Description', models.CharField(default='', max_length=300)),
                ('Venue', models.CharField(default='', max_length=50)),
                ('Entry_fee', models.IntegerField(default=0)),
                ('Prize', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='home/images')),
                ('City', models.CharField(max_length=20)),
            ],
        ),
    ]
