# Generated by Django 3.1.7 on 2021-03-03 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Date',
            field=models.DateField(default=datetime.datetime(2021, 3, 3, 13, 24, 6, 592248, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
