# Generated by Django 3.1.7 on 2021-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210303_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Event_category',
            field=models.CharField(choices=[('BATTLES', 'Batlle'), ('WORKSHOPS', 'Workshop'), ('CLASSES', 'Classes')], default='', max_length=10),

        ),
    ]
