# Generated by Django 3.1.6 on 2021-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210305_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Event_category',
            field=models.CharField(choices=[('Hip-HOP', 'HIP-HOP'), ('Popping', 'Popping'), ('Breaking', 'Breaking')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='events',
            name='Event_type',
            field=models.CharField(choices=[('BATTLES', 'Batlle'), ('WORKSHOPS', 'Workshop'), ('CLASSES', 'Classes')], default='', max_length=10),
        ),
    ]
