# Generated by Django 3.0.2 on 2021-03-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210320_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
